import Head from 'next/head'
import Home from "../pages/home/index";
import Header from "../components/layout/Header";

export default function Index() {
    return (
        <div className="">
            <Head>
                <title>Next App MCK</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Home/>
        </div>
    )
}
